  _target_: dataset.preprocess.stacked_hourglass.PSMNet

  maxdisp: 192
  lr: 0.001
  lr_mode: 'multi'
  loadmodel: '../dataset/preprocess/disparity/psmnet/psmnet_flyingthings_24hrs_hahnec.ckpt'
  beta_lo: 0.9
  beta_hi: 0.999