slam:
  surf_thr: 300.0
  match_cross_check: False
  lowes_ratio: 0.7
  node_spacing: 20

img_size:
  - 640
  - 512

sample: 1

depth_clipping:
  - 0
  - 300 # in mm

viewer:
  enable: False
  show: True
  matches: True
  view_synthesis: True