model:
  pretrained: ../alley_oop/network_core/raft/pretrained/raft-things.pth
  iters: 12
  dropout: 0.0
  small: False
  RGBD: False
  pose_scale: 1.0
  mode: lbgfs #mlp # horn
  use_weights: True
  activation: sigmoid

data:
  train:
    type: Intuitive
    basepath: /storage/workspaces/artorg_aimi/ws_00000/innosuisse_surgical_robot/01_Datasets/05_slam/intuitive_human
    sequences:
      - dataset_1_0
      - dataset_1_1
      - dataset_1_2
      - dataset_1_3
      - dataset_1_4
      - dataset_1_5
      - dataset_1_6
      - dataset_3_0
      - dataset_3_1
      - dataset_3_2
      - dataset_3_3
      - scared_dataset_1
      - scared_dataset_2
      - scared_dataset_3
      - scared_dataset_6
    step:
      - 1
      - 30
    samples: 1500

  val:
    type: Intuitive
    basepath: /storage/workspaces/artorg_aimi/ws_00000/innosuisse_surgical_robot/01_Datasets/05_slam/intuitive_human
    sequences:

    step: 3
    samples: 50

  val2:
    type: Intuitive
    basepath: /storage/workspaces/artorg_aimi/ws_00000/innosuisse_surgical_robot/01_Datasets/05_slam/intuitive_human
    sequences:
      - scared_dataset_7
      - scared_dataset_8
      - scared_dataset_9
    step: 1
    samples: 50

train:
  batch_size: 8
  learning_rate: 1.0e-5
  weight_decay: 5.0e-5
  epsilon: 1.0e-8
  epochs: 100000
  gamma: 0.8
  grad_clip: 1.0
  loss_weights:
    pose: 1.0
    2d: 0.0
    3d: 0.0
    flow: 0.0
  add_noise: False
  freeze_flow_steps: 1000000000000000000

val:
  batch_size: 10

image_shape:
  - 512
  - 640
depth_scale: 250